apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/namespace.yaml
  - manifests/configmap.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml
  - todo-backend/manifests/deployment.yaml
  - todo-backend/manifests/service.yaml
  - todo-backend/manifests/cronjob.yaml
images:
  - name: PROJECT/PROJECT_IMAGE
    newName: europe-north1-docker.pkg.dev/oo-devops-k8s-2026/dwk-repo/project
  - name: PROJECT/TODO_BACKEND_IMAGE
    newName: europe-north1-docker.pkg.dev/oo-devops-k8s-2026/dwk-repo/todo-backend
