apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: default
spec:
  traffic:
    - revisionName: hello-v1
      percent: 50
    - latestRevision: true
      percent: 50
  template:
    metadata:
      name: hello-v2
    spec:
      containers:
        - name: user-container
          image: ghcr.io/knative/helloworld-go:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 0
            successThreshold: 1
          env:
            - name: TARGET
              value: Knative
