apiVersion: v1
kind: ConfigMap
metadata:
  namespace: project
  name: project-config
data:
  PORT: "3000"
  TODO_BACKEND_URL: "http://todo-backend:3000"
  MESSAGE: "Hello from Kubernetes"
  IMAGE_URL: "https://picsum.photos/1200"
  IMAGE_CACHE_MINUTES: "10"
  POSTGRES_HOST: "todo-postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "todos"
  POSTGRES_USER: "postgres"
  DB_RETRY_MS: "3000"
