apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-production
resources:
- ../../base
- namespace.yaml
- ../../base/production-backup
patches:
- patch: |-
    - op: replace
      path: /data/NATS_SUBJECT
      value: todos.events.production
    - op: replace
      path: /data/NATS_QUEUE
      value: todo-broadcasters-production
    - op: add
      path: /data/BROADCAST_MODE
      value: forward
  target:
    kind: ConfigMap
    name: project-config
images:
- name: PROJECT/BROADCASTER_IMAGE
  newName: europe-north1-docker.pkg.dev/oo-devops-k8s-2026/dwk-repo/todo-broadcaster
  newTag: a7bc5f40f094600dc90c2dec84e46db6fffed744
- name: PROJECT/PROJECT_IMAGE
  newName: europe-north1-docker.pkg.dev/oo-devops-k8s-2026/dwk-repo/project
  newTag: a7bc5f40f094600dc90c2dec84e46db6fffed744
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: europe-north1-docker.pkg.dev/oo-devops-k8s-2026/dwk-repo/todo-backend
  newTag: a7bc5f40f094600dc90c2dec84e46db6fffed744
