apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummysite-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummysite-controller
  template:
    metadata:
      labels:
        app: dummysite-controller
    spec:
      serviceAccountName: dummysite-controller
      containers:
        - name: controller
          image: europe-north1-docker.pkg.dev/oo-devops-k8s-2026/dwk-repo/dummysite-controller:5.1-amd64
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
