apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/oozan/devops-with-kubernetes.git
    targetRevision: main
    path: exercise-4.8/project
  destination:
    server: https://kubernetes.default.svc
    namespace: project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
