apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
  - namespace.yaml
  - waypoint.yaml
  - configmap.yaml
  - log-output.yaml
  - greeters.yaml
  - greeter-route.yaml
