apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: project
  name: wikipedia-todo
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: wikipedia-todo
              image: curlimages/curl:8.10.1
              command:
                - sh
                - -c
                - |
                  URL=$(curl -s -I https://en.wikipedia.org/wiki/Special:Random | grep -i '^location:' | awk '{print $2}' | tr -d '\r')
                  curl -s -X POST http://todo-backend.project:3000/todos \
                    -H "Content-Type: application/json" \
                    -d "{\"todo\":\"Read $URL\"}"
