apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: PROJECT/TODO_BACKEND_IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: PORT
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: POSTGRES_USER
            - name: DB_RETRY_MS
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: DB_RETRY_MS
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-postgres-secret
                  key: POSTGRES_PASSWORD
