apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: PROJECT/TODO_BACKEND_IMAGE
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 2
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: PORT
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: POSTGRES_USER
            - name: DB_RETRY_MS
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: DB_RETRY_MS
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: NATS_URL
            - name: NATS_SUBJECT
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: NATS_SUBJECT
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-postgres-secret
                  key: POSTGRES_PASSWORD
