apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-staging
resources:
- ../../base
- namespace.yaml
patches:
- patch: |-
    - op: replace
      path: /data/NATS_SUBJECT
      value: todos.events.staging
    - op: replace
      path: /data/NATS_QUEUE
      value: todo-broadcasters-staging
    - op: add
      path: /data/BROADCAST_MODE
      value: log
  target:
    kind: ConfigMap
    name: project-config
images:
- name: PROJECT/BROADCASTER_IMAGE
  newName: europe-north1-docker.pkg.dev/oo-devops-k8s-2026/dwk-repo/todo-broadcaster
  newTag: 467733b397e942295efc460206e5d6b5b58d8c8a
- name: PROJECT/PROJECT_IMAGE
  newName: europe-north1-docker.pkg.dev/oo-devops-k8s-2026/dwk-repo/project
  newTag: 467733b397e942295efc460206e5d6b5b58d8c8a
- name: PROJECT/TODO_BACKEND_IMAGE
  newName: europe-north1-docker.pkg.dev/oo-devops-k8s-2026/dwk-repo/todo-backend
  newTag: 467733b397e942295efc460206e5d6b5b58d8c8a
