apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: project
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data-pvc
      containers:
        - name: project
          image: PROJECT/PROJECT_IMAGE
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: project-config
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/files
