apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: project
  name: todo-database-backup
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: todo-database-backup
              image: PROJECT/BACKUP_IMAGE
              imagePullPolicy: IfNotPresent
              env:
                - name: BACKUP_BUCKET
                  value: oo-devops-k8s-2026-todo-backups
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /var/secrets/google/key.json
                - name: CLOUDSDK_CONFIG
                  value: /tmp/gcloud
                - name: POSTGRES_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: project-config
                      key: POSTGRES_HOST
                - name: POSTGRES_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: project-config
                      key: POSTGRES_PORT
                - name: POSTGRES_DB
                  valueFrom:
                    configMapKeyRef:
                      name: project-config
                      key: POSTGRES_DB
                - name: POSTGRES_USER
                  valueFrom:
                    configMapKeyRef:
                      name: project-config
                      key: POSTGRES_USER
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: todo-postgres-secret
                      key: POSTGRES_PASSWORD
              resources:
                requests:
                  cpu: 50m
                  memory: 256Mi
                limits:
                  cpu: 250m
                  memory: 512Mi
              volumeMounts:
                - name: storage-key
                  mountPath: /var/secrets/google
                  readOnly: true
                - name: temporary-files
                  mountPath: /tmp
          volumes:
            - name: storage-key
              secret:
                secretName: storage-sa-key
            - name: temporary-files
              emptyDir: {}
